---
- name: Remove old InfluxDB apt repository entry
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/repos_influxdata_com_{{ ansible_distribution | lower }}.list
    state: absent

- name: Remove InfluxDB apt signing key from default apt keyring
  ansible.builtin.apt_key:
    id: "{{ influxdb_apt_key_fingerprint }}"
    keyring: /etc/apt/trusted.gpg
    state: absent

- name: Import InfluxDB packaging GPG signing key
  ansible.builtin.apt_key:
    id: "{{ influxdb_apt_key_fingerprint }}"
    url: https://repos.influxdata.com/influxdb.key
    keyring: /usr/share/keyrings/influxdb.gpg
    state: present

- name: Add InfluxDB repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/influxdb.gpg]
      https://repos.influxdata.com/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    filename: influxdb
    state: present

- name: Install InfluxDB packages
  ansible.builtin.apt:
    name: influxdb
    state: present

# If we're moving the influxdb root directory then it might not exist
- name: Check influxdb database directory exists
  ansible.builtin.file:
    path: "{{ influxdb_root }}"
    state: directory
    owner: influxdb
    group: influxdb
    mode: u=rwx,g=rx,o=rx

# Warn users that /etc/influxdb/influxdb.conf is managed by ansible (even
# though only some of the lines actually are).
- name: Mark /etc/influxdb/influxdb.conf as managed by ansible
  ansible.builtin.lineinfile:
    dest: /etc/influxdb/influxdb.conf
    line: "# Ansible managed"
    state: present
    insertbefore: BOF

# the influxdb config file moves quickly, so just update the known issues
- name: Configure /etc/influxdb/influxdb.conf
  community.general.ini_file:
    path: /etc/influxdb/influxdb.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: u=rw,g=r,o=r
  loop: "{{ influxdb_settings }}"
  loop_control:
    label: "{{ item.option }}={{ item.value }}"
  notify: restart influxdb

# Influx needs to be running so packages can configure it during postinst
- name: Check influxdb is running
  ansible.builtin.service:
    name: influxdb.service
    state: started
